version: '3'
services:
  chat-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://localhost:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"